# mySettings
# 2021/6/29
# -*- coding:utf-8 -*-



# 账号和密码
test_login:
  - url: 'http://120.55.190.222:38090/#/login'
    username: 'f8cfa9c818e743c39c3523fb3255501c'
    password: '123456'



init_driver:
  - # 隐式等待的超时时间s
    implicitly_time_out: 5
    url: 'http://120.55.190.222:38090/#/login'
    username: 'f8cfa9c818e743c39c3523fb3255501c'
    password: '123456'

    # 显示等待超时时间
#    time_out: 5
#    # 显示等待轮询时间
#    poll_frequency: 0.5

